# Generated by Django 5.0.2 on 2024-03-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodule',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Not Started', 'Not Started'), ('Testing', 'Testing')], max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Not Started', 'Not Started'), ('Testing', 'Testing')], max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Not Started', 'Not Started'), ('Testing', 'Testing')], default='Not Started', max_length=100),
        ),
    ]
