# Generated by Django 5.0.2 on 2024-03-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_usertask_created_at_usertask_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
